#ifndef GLOBALCONSTANTS_H
#define GLOBALCONSTANTS_H

const double SCALE_FACTOR = 1.5;

const int WINDOW_WIDTH = 800*SCALE_FACTOR;
const int WINDOW_HEIGHT = 450*SCALE_FACTOR;
const int ACCELERATION = 7000*SCALE_FACTOR;

const int FIRE_RATE = 0.25;

const int JOYSTICK_DEAD_ZONE = 8000;

#endif //GLOBALCONSTANTS_H
